grails:
  profile: web-plugin
  codegen:
    defaultPackage: grails.plugins.elasticsearch
  spring:
    transactionManagement:
      proxies: false
  gorm:
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
  databinding:
    dateFormats: ["yyyy-MM-dd'T'HH:mm:ss.SSSZ"]
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlets: html
        taglib: none
        staticparts: none

info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'

spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false
  jmx:
    unique-names: true
  devtools:
    restart:
      exclude:
        - grails-app/views/**
        - grails-app/i18n/**
        - grails-app/conf/**

management:
  endpoints:
    enabled-by-default: false

elasticSearch:
  date:
    formats: ["yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"]
  client:
    connectTimeout: 2
    socketTimeout: 30
    mode: local
    hosts:
      - {host: localhost, port: 9200}
    transport.sniff: false
    username: zzb-elasticsearch
    password: /+mh&K@2sF('X7J_
  datastoreImpl: hibernateDatastore
  defaultExcludedProperties: ['password']
  disableAutoIndex: false
  index:
    compound_format: true
    store.type: fs
    settings:
      analysis:
        filter:
          replace_synonyms:
            type: synonym
            synonyms: ['abc => xyz']
        analyzer:
          test_analyzer:
            tokenizer: standard
            filter: ['lowercase']
          repl_analyzer:
            tokenizer: standard
            filter: ['lowercase', 'replace_synonyms']
  snapshots:
    repository:
      name: ss_repo
      config:
        type: fs
        settings:
          ## see https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-register-repository.html for all params
          location: snapshots
          compress: false
          chunk_size: 20MB
    policies:
      - id: nightly-snapshots
        config:
          schedule: "0 30 1 * * ?"
          name: "<nightly-snap-{now/d}>"
          repository: "ss_repo"
          config:
            indices: ["*"]
            retention:
              expire_after: "30d"
              min_count: 5
              max_count: 50
      - id: hourly-snapshots
        config:
          schedule: "0 0 */1 * * ?"
          name: "<hourly-snap-{now/d}>"
          repository: "ss_repo"
          config:
            indices: ["*"]
            retention:
              expire_after: "1d"
              min_count: 5
              max_count: 24

  unmarshallComponents: true
  searchableProperty:
    name: searchable
  includeTransients: false
  includeDomainTypeName: true

environments:
  production:
    elasticSearch:
      client:
        mode: node

hibernate:
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
  dbCreate: create-drop
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password:
  url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE